export const SET_VACATIONS = 'SET_VACATIONS';
export const FETCH_VACATIONS_FAILED = 'FETCH_VACATIONS_FAILED';

export const ADD_USER_VACATION = 'ADD_USER_VACATION';
export const ADD_USER_VACATION_FAILED = 'ADD_USER_VACATION_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';