export const SET_VACATIONS = 'SET_VACATIONS';
export const FETCH_VACATIONS_FAILED = 'FETCH_VACATIONS_FAILED';

export const ADD_USER_VACATION = 'ADD_USER_VACATION';
export const ADD_USER_VACATION_FAILED = 'ADD_USER_VACATION_FAILED';